apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    name: command-demo
spec:
  containers:
  - name: command-demo
    image: wuyiccc/nginx
    imagePullPolicy: Never
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure