apiVersion: v1
kind: Pod
metadata:
  name: myapp2
  labels:
      app: myapp2
spec:
  containers:
  - name: myapp2
    image: busybox:1.28
    imagePullPolicy: Never
    command: ['sh', '-c']
    args: ["printf SERVICE_IP=$SERVICE_IP"]
    env:
    - name: "SERVICE_IP"
      value: "192.168.137.160"
    resources:
        limits:
            memory: "128Mi"
            cpu: "200m"
  restartPolicy: OnFailure             
