apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: myapp
      image: wuyiccc/nginx:latest
      imagePullPolicy: Never
      volumeMounts:
          # 容器内部路径
        - mountPath: /test-nginx
          name: host-path-volume
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
  volumes:
      # 不能出现大写
    - name: host-path-volume
      hostPath:
        # 宿主机路径
        path: /tmp/nginx
        type: DirectoryOrCreate