apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: pi
          image: wuyiccc/nginx:latest
          imagePullPolicy: Never
          command: ['sh', '-c', 'echo "Hello, K8s"']
      restartPolicy: Never
  backoffLimit: 4