apiVersion: v1
kind: Pod
metadata:
  name: busy33
  labels:
    app: busy33
spec:
  dnsPolicy: ClusterFirstWithHostNet
  hostname: busy33
  containers:
    - name: busybox-container
      image: busybox:1.28
      imagePullPolicy: Never
      command: ["sleep", "3600"]