apiVersion: v1
kind: Pod
metadata:
  name: pod-test
spec:
  containers:
    - name: test
      image: busybox:1.28
      imagePullPolicy: Never
      command: ["/bin/sh", "-c", "env"]
      envFrom:
        - configMapRef:
            name: appvar
  restartPolicy: Never